import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import { teamLogic } from 'scenes/teamLogic'

import { externalDataDestinationsList } from 'products/warehouse_sources/frontend/generated/api'
import { ExternalDataDestinationApi } from 'products/warehouse_sources/frontend/generated/api.schemas'

import { sourceWizardLogic } from '../sourceWizardLogic'
import { defaultDestinationIds, toggleDestinationId } from './destinationStepUtils'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface destinationStepLogicValues {
    currentTeamId: number | null // teamLogic
    selectedIds: string[] // sourceWizardLogic
    destinations: ExternalDataDestinationApi[]
    destinationsLoading: boolean
    hasLoaded: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface destinationStepLogicActions {
    setWizardDestinationIds: (destinationIds: string[]) => any // sourceWizardLogic
    loadDestinations: () => any
    loadDestinationsSuccess: (destinations: ExternalDataDestinationApi[], payload?: any) => any
    selectDefault: () => { value: true }
    toggleDestination: (destinationId: string) => {
        destinationId: string
    }
}

export interface destinationStepLogicMeta {
    key: undefined
    __keaTypeGenInternalSelectorTypes: {
        selectedIds: (wizardDestinationIds: string[]) => string[]
    }
}

export type destinationStepLogicType = MakeLogicType<
    destinationStepLogicValues,
    destinationStepLogicActions,
    Record<string, never>,
    destinationStepLogicMeta
>

export const destinationStepLogic = kea<destinationStepLogicType>([
    path(['products', 'data_warehouse', 'frontend', 'scenes', 'NewSourceScene', 'destinationStepLogic']),
    connect(() => ({
        values: [teamLogic, ['currentTeamId'], sourceWizardLogic, ['wizardDestinationIds']],
        actions: [sourceWizardLogic, ['setWizardDestinationIds']],
    })),
    actions({
        toggleDestination: (destinationId: string) => ({ destinationId }),
        selectDefault: true,
    }),
    loaders(({ values }: any) => ({
        destinations: [
            [] as ExternalDataDestinationApi[],
            {
                loadDestinations: async () => {
                    const response = await externalDataDestinationsList(String(values.currentTeamId))
                    return response.results ?? []
                },
            },
        ],
    })),
    reducers({
        hasLoaded: [
            false,
            {
                loadDestinationsSuccess: () => true,
            },
        ],
    }),
    selectors({
        // The wizard owns the picked set, so it survives stepping back and forth and is still
        // there when the source is created.
        selectedIds: [(s: any) => [s.wizardDestinationIds], (ids: string[]) => ids],
    }),
    listeners(({ values, actions }: any) => ({
        toggleDestination: ({ destinationId }: { destinationId: string }) => {
            actions.setWizardDestinationIds(toggleDestinationId(values.wizardDestinationIds, destinationId))
        },
        selectDefault: () => {
            actions.setWizardDestinationIds(defaultDestinationIds(values.destinations, values.wizardDestinationIds))
        },
    })),
    afterMount(({ actions }: any) => {
        actions.loadDestinations()
    }),
])
