# Generated by Django 5.2.17 on 2026-08-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp_store", "0026_agent_grant_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpservertemplate",
            name="oauth_scope_allowlist",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
