from products.tasks.backend.facade.sandbox import SandboxTemplate

WIZARD_TIMEOUT_SECONDS = 45 * 60
WIZARD_TIMEOUT_EXIT_CODE = 124
WIZARD_ERROR_DETAIL_LENGTH = 2000

SANDBOX_EXECUTION_TIMEOUT_SECONDS = WIZARD_TIMEOUT_SECONDS + 120
SANDBOX_TTL_SECONDS = 75 * 60
SANDBOX_TEMPLATE_BASE = SandboxTemplate.DEFAULT_BASE
SANDBOX_MEMORY_GB = 4
SANDBOX_CPU_CORES = 2
SANDBOX_DISK_SIZE_GB = 16
