# Generated by Django 5.2.17 on 2026-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wizard", "0018_add_run_cancellation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="wizardworker",
            name="resource_usage",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
