import { MakeLogicType, actions, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { forms } from 'kea-forms'
import type { DeepPartialMap, ValidationErrorType } from 'kea-forms'

import { integrationsLogic } from 'lib/integrations/integrationsLogic'
import { lemonToast } from 'lib/lemon-ui/LemonToast/LemonToast'
import { teamLogic } from 'scenes/teamLogic'

import type { IntegrationType } from '~/types'

import {
    externalDataDestinationsCreate,
    externalDataDestinationsPartialUpdate,
} from 'products/warehouse_sources/frontend/generated/api'
import { ExternalDataDestinationApi } from 'products/warehouse_sources/frontend/generated/api.schemas'

export interface DestinationModalLogicProps {
    /** Distinguishes the source-level modal from the schema-level one so they keep separate form state. */
    modalKey: string
    onSaved: (destination: ExternalDataDestinationApi) => void
}

export interface DestinationFormValues {
    name: string
    integrationId: number | null
    database: string
    schema: string
}

const NEW_DESTINATION_FORM: DestinationFormValues = {
    name: '',
    integrationId: null,
    database: 'postgres',
    schema: 'public',
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface destinationModalLogicValues {
    integrations: IntegrationType[] | null // integrationsLogic
    currentTeamId: number | null // teamLogic
    destinationForm: DestinationFormValues
    destinationFormChanged: boolean
    destinationFormErrors: DeepPartialMap<DestinationFormValues, ValidationErrorType>
    destinationFormHasErrors: boolean
    destinationFormTouched: boolean
    destinationFormValidationErrors: DeepPartialMap<DestinationFormValues, ValidationErrorType>
    editing: ExternalDataDestinationApi | null
    isDestinationFormSubmitting: boolean
    isOpen: boolean
    postgresIntegrations: IntegrationType[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface destinationModalLogicActions {
    loadIntegrations: () => any // integrationsLogic
    closeModal: () => { value: true }
    openForCreate: () => { value: true }
    openForEdit: (destination: ExternalDataDestinationApi) => {
        destination: ExternalDataDestinationApi
    }
    setDestinationFormValue: (key: string, value: any) => any
    setDestinationFormValues: (values: Partial<DestinationFormValues>) => any
    submitDestinationForm: () => void
}

export interface destinationModalLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        postgresIntegrations: (integrations: IntegrationType[] | null) => IntegrationType[]
    }
}

export type destinationModalLogicType = MakeLogicType<
    destinationModalLogicValues,
    destinationModalLogicActions,
    DestinationModalLogicProps,
    destinationModalLogicMeta
>

export const destinationModalLogic = kea<destinationModalLogicType>([
    path(['products', 'data_warehouse', 'frontend', 'shared', 'logics', 'destinationModalLogic']),
    props({} as DestinationModalLogicProps),
    key((props: DestinationModalLogicProps) => props.modalKey),
    connect(() => ({
        values: [teamLogic, ['currentTeamId'], integrationsLogic, ['integrations']],
        actions: [integrationsLogic, ['loadIntegrations']],
    })),
    actions({
        openForCreate: true,
        openForEdit: (destination: ExternalDataDestinationApi) => ({ destination }),
        closeModal: true,
    }),
    reducers({
        isOpen: [
            false,
            {
                openForCreate: () => true,
                openForEdit: () => true,
                closeModal: () => false,
            },
        ],
        editing: [
            null as ExternalDataDestinationApi | null,
            {
                openForCreate: () => null,
                openForEdit: (_, { destination }) => destination,
                closeModal: () => null,
            },
        ],
    }),
    selectors({
        postgresIntegrations: [
            (s: any) => [s.integrations],
            (integrations: IntegrationType[] | null): IntegrationType[] =>
                (integrations ?? []).filter((integration) => integration.kind === 'postgresql'),
        ],
    }),
    forms(({ values, props, actions }: any) => ({
        destinationForm: {
            defaults: NEW_DESTINATION_FORM,
            errors: ({ name, integrationId }: DestinationFormValues) => ({
                name: !name?.trim() ? 'Give this destination a name' : undefined,
                integrationId: integrationId ? undefined : 'Pick a connection',
            }),
            submit: async (formValues: DestinationFormValues) => {
                const payload = {
                    type: 'Postgres' as const,
                    name: formValues.name.trim(),
                    integration: formValues.integrationId,
                    config: { database: formValues.database, schema: formValues.schema },
                }
                const teamId = String(values.currentTeamId)
                const saved = values.editing
                    ? await externalDataDestinationsPartialUpdate(teamId, values.editing.id, payload)
                    : await externalDataDestinationsCreate(teamId, payload)

                lemonToast.success(values.editing ? 'Destination updated' : 'Destination added')
                actions.closeModal()
                props.onSaved(saved)
            },
        },
    })),
    listeners(({ actions, values }: any) => ({
        openForCreate: () => {
            actions.loadIntegrations()
            actions.setDestinationFormValues({
                ...NEW_DESTINATION_FORM,
                // One connection usually means one obvious answer; preselect it.
                integrationId: values.postgresIntegrations.length === 1 ? values.postgresIntegrations[0].id : null,
            })
        },
        openForEdit: ({ destination }: { destination: ExternalDataDestinationApi }) => {
            actions.loadIntegrations()
            const config = (destination.config ?? {}) as Record<string, unknown>
            actions.setDestinationFormValues({
                name: destination.name,
                integrationId: destination.integration ?? null,
                database: typeof config.database === 'string' ? config.database : 'postgres',
                schema: typeof config.schema === 'string' ? config.schema : 'public',
            })
        },
    })),
])
