# Generated by Django 5.2.17 on 2026-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0099_backfill_first_visible_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalreport",
            name="inbox_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
